# -------------------- VARIABLES GLOBALES ALGORITHME GENETIQUE -------------------- #
import sys

ELITE = 0.6
ELITE_RATIO_RANG = 0.01
ELITE_RATIO_ADAPTATION = 0.5
ELITE_RATIO_UNIFORME = 1 - ELITE_RATIO_RANG - ELITE_RATIO_ADAPTATION
NB_REPRODUCTION_MEILLEUR = 0.3
NB_REPRODUCTION_ALEATOIRE = 0.1
NB_REPRODUCTION_BON_PAS_BON = 0.1
MUTATION = 0.1

INDIVIDU = None
NB_INDIVIDU = 100
COMPTEUR_INDIVIDU = 1

NB_GENERATION = 1000
COMPTEUR_GENERATION = 1

NB_MAX_NEURONES_PAR_LAYER = 72
NB_MAX_LAYER_PAR_NETWORK = 10

sys.setrecursionlimit(NB_INDIVIDU * NB_MAX_LAYER_PAR_NETWORK * NB_MAX_NEURONES_PAR_LAYER)